<?xml version="1.0"?>
<!-- Copyright 2011-2020 The MathWorks, Inc. -->
<rsccat version="1.0" locale="en_US" product="parallel">
  <message>
    <entry key="AddAdditionalPathsToPath" context="error">Error encountered while adding AdditionalPaths to MATLAB path.</entry>
    <entry key="AddAttachedFilesToPath" context="error">Error encountered while adding AttachedFiles to MATLAB path.</entry>
    <entry key="AddAttachedFilesToPathZipError" context="error">Error encountered while unzipping AttachedFiles. This can happen when the AttachedFiles are larger than 4GB.</entry>
    <entry key="AutoAttachedFiles" context="uistring" note="{0} - the task function name">Files that are automatically added for ''{0}'':\n{1}</entry>
    <entry key="CannotLoadFromMatFile" context="error">Task objects cannot be loaded from a MAT file or directly created from a constructor.</entry>
    <entry key="DiaryIncomplete" context="warning">The diary of this task might be incomplete because the task is still running.</entry>
    <entry key="EvaluateTaskUnexpectedError" context="error">UNEXPECTED ERROR in dctEvaluateTask/nEvaluateTask.</entry>
    <entry key="GetInputData" context="error">Error encountered while getting input data from the task.</entry>
    <entry key="InvalidDeleteSyntax" context="error">Invalid syntax. Use "delete(task)" to delete a task.</entry>
    <entry key="MJSDataStorageFailed" context="error">Failed to read/write task data to the database.</entry>
    <entry key="MJSTaskNotFound" context="error">The task could not be found.</entry>
    <entry key="MJSUnableToSubmitResult" context="error">Unable to return results to jobmanager. The reason is :\n{0}</entry>
    <entry key="NoAutoAttachedFiles" context="uistring" note="{0} - the task function name">No files automatically added for ''{0}''.</entry>
    <entry key="PostTaskUnexpectedError" context="error">UNEXPECTED ERROR in dctEvaluateTask/nPostTaskFinish.</entry>
    <entry key="PropertySetVersionMismatch" context="error">Properties must be set on tasks in the same MATLAB release that created the task: {0}</entry>
    <entry key="TaskCancellationFailed" context="warning">The cluster failed to cancel task execution. The error was: {0}</entry>
    <entry key="TaskDestructionFailed" context="warning">The cluster failed to destroy the task correctly. The error was: {0}</entry>
    <entry key="TaskFinishUserError" context="error">Error thrown in user-supplied taskFinish function ''{0}''.</entry>
    <entry key="TaskResultTooLarge" context="error">The task result was too large to be stored.</entry>
    <entry key="TaskStartupUserError" context="error">Error thrown in user-supplied taskStartup function ''{0}''.</entry>
    <entry key="UserCancellation" context="error">The task was cancelled by user "{0}" on machine "{1}".</entry>
    <entry key="UserCancellationWithMessage" context="error">The task was cancelled by user "{0}" on machine "{1}" with message: "{2}".</entry>
    <entry key="WarningLimitReached" context="warning">Maximum number of warnings reached. Further warnings will be discarded.</entry>
  </message>
</rsccat>
